Repository PurpleDynamics/PEA_Project, pull requests merged in 2024-01, with the labels that each got.

#3 PR/PD-39: PR Template 수정
  .github/PULL_REQUEST_TEMPLATE.md
Labels: docs

#5 PR/PD-42: styled components 의존성 추가 및 디자인 토큰 작성했습니다.
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/App.test.js
  src/assets/fonts/index.css
  src/assets/fonts/soyo-maple-bold.ttf
  src/assets/fonts/soyo-maple-regular.ttf
  src/index.css
  src/index.js
  src/libs/styled-components/global-styles.jsx
  src/libs/styled-components/index.js
  src/libs/styled-components/reference-tokens/break-point.js
  src/libs/styled-components/reference-tokens/color.js
  src/libs/styled-components/reference-tokens/font-size.js
  src/libs/styled-components/reference-tokens/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: config

#6 PR/PD-54 auto-color 기능을 추가하였습니다.
  src/utils/auto-color-manager.js
  src/utils/index.js
Labels: feat

#7 PR/PD-41: react router dom 의존성 추가 및 설정 파일 생성 했습니다.
  package-lock.json
  package.json
  src/components/index.js
  src/components/layouts/layout.jsx
  src/index.js
  src/libs/react-router-dom/router.jsx
  src/pages/index.js
  src/pages/my-info-page.jsx
  src/pages/products/detail-product-page.jsx
  src/pages/products/product-list-page.jsx
  src/pages/products/register-product-page.jsx
  src/pages/products/used-product-page.jsx
  src/pages/sign/signin-page.jsx
  src/pages/sign/signup-page.jsx
Labels: feat, config

#9 PR/PD-64: react-icons 의존성 추가했습니다.
  package-lock.json
  package.json
Labels: config

#8 PR/PD-37: 공용 컴포넌트 "CategoryToggle" 작성했습니다.
  src/components/category-toggle.jsx
  src/components/index.js
Labels: design

#12 PR/PD-65: 공용컴포넌트 "ResponsiveIcon" 작성했습니다.
  src/components/commons/index.js
  src/components/commons/responsive-icon.jsx
Labels: design

#13 PR/PD-36: 공용컴포넌트 "Button" 작성했습니다.
  src/components/commons/button.jsx
  src/components/commons/index.js
  src/libs/styled-components/global-styles.jsx
Labels: design

#11 PR/PD-43: 공용 컴포넌트 "Input" 작성했습니다.
  package-lock.json
  package.json
  src/components/commons/index.js
  src/components/commons/input.jsx
Labels: design

#14 PR: 충돌 미해결 merge 된 건에 대하여 해결했습니다.
  src/components/commons/category-toggle.jsx
  src/components/commons/index.js
  src/components/index.js
Labels: fix

#10 PR/PD-51: 공용컴포넌트 Layout(Header,Footer)작업했습니다.
  src/components/commons/index.js
  src/components/commons/responsive-icon.jsx
  src/components/commons/search-bar.jsx
  src/components/layouts/footer.jsx
  src/components/layouts/header.jsx
  src/components/layouts/index.js
  src/components/layouts/layout.jsx
  src/libs/react-router-dom/router.jsx
Labels: design

#16 PE/PD-41: 권한 여부에 따라 접근 페이지 제어 기능 구현
  .github/PULL_REQUEST_TEMPLATE.md
  src/components/layouts/layout.jsx
  src/index.js
  src/libs/react-router-dom/admin-router.jsx
  src/libs/react-router-dom/index.js
  src/libs/react-router-dom/router.jsx
  src/pages/404-page.jsx
  src/pages/detail-product-page.jsx
  src/pages/index.js
  src/pages/product-list-page.jsx
  src/pages/register-product-page.jsx
  src/pages/signin-page.jsx
  src/pages/signup-page.jsx
  src/pages/used-product-page.jsx
Labels: config

#19 PR/PD-41: useEffect 추가 ( 빠른 merge 부탁드립니다. 급함!!!)
  src/libs/react-router-dom/admin-router.jsx
Labels: fix

#17 PR/PD-36: 버튼 너비를 외부에서 주입하도록 변경
  src/components/commons/button.jsx
Labels: refactor

#22 PR: input, button 등 공용컴포넌트 상세 수정한 사항입니다.
  package-lock.json
  src/components/commons/button.jsx
  src/components/commons/input.jsx
Labels: fix

#24 PR/PD-69: axios 의존성 추가 했습니다.
  package-lock.json
  package.json
Labels: config
