Repository PurpleDynamics/PEA_Project, pull requests merged in 2024-02, with the labels that each got.

#15 PR:PD-38: 공용컴포넌트 "ProductCard" 작성했습니다.
  src/components/commons/category-toggle.jsx
  src/components/commons/highlighted-text.jsx
  src/components/commons/index.js
  src/components/commons/product-card.jsx
  src/utils/data-calculator.js
  src/utils/index.js
Labels: design

#23 PR/PD-61: compression-container 생성
  src/components/commons/compression-container.jsx
Labels: design

#29 PR:PD-53: 공용컴포넌트 banner작업했습니다.
  src/components/commons/banner.jsx
  src/components/commons/index.js
Labels: design

#27 PR/PD-50: 모달 등 오버레이가 필요한 컴포넌트 on/off 로직을 작성했습니다.
  src/components/commons/index.js
  src/components/overlay/index.js
  src/components/overlay/overlay-base.js
  src/contexts/index.js
  src/contexts/overlay.jsx
  src/hooks/index.js
  src/hooks/use-overlay.js
  src/index.js
Labels: feat

#26 PR/PD-67: signup-page 작업했습니다.
  src/components/commons/input.jsx
  src/constants/index.js
  src/constants/validate-message.js
  src/pages/signup-page.jsx
Labels: design

#30 PR: `src>components>commons` barrel-file 중 중복된 컴포넌트 삭제합니다.
  src/components/commons/compression-container.jsx
  src/components/commons/index.js
Labels: fix

#28 PR/PD-68: 최근 본 상품 UI 관련 컴포넌트 작성했습니다.
  src/components/commons/index.js
  src/components/commons/recent-product-list.jsx
  src/components/commons/side-chat-button.jsx
  src/components/commons/spacer.jsx
  src/components/commons/top-button.jsx
  src/components/layouts/layout.jsx
Labels: feat, design

#32 PR/PD-48: login-page 생성했습니다.
  src/pages/signin-page.jsx
Labels: design

#38 PR/PD-68: RecentProductList 컴포넌트 background-color 지정 및 요소 Re-sizing 변경
  src/components/commons/recent-product-list.jsx
  src/components/commons/side-chat-button.jsx
Labels: design

#21 PR/PD-66: 공용컴포넌트 modal 작성했습니다.
  src/components/overlay/modal.jsx
Labels: design

#31 PR/PD-72: 공용컴포넌트 iconAndText 작업했습니다.
  src/components/commons/icon-and-text.jsx
  src/components/commons/index.js
  src/utils/data-editor.js
  src/utils/date-calculator.js
  src/utils/index.js
Labels: design

#39 PR/PD-50: 오버레이 컴포넌트 에서 다른 오버레이 컴포넌트를 랜더할 수 있도록 기능 추가했습니다.
  src/components/overlay/overlay-base.jsx
  src/contexts/overlay.jsx
Labels: feat, config

#36 PR/PD-62: 상품 정보 반환에 대한 mock data 생성 및 응답 로직 작성했습니다.
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/index.js
  src/libs/axios/ads/index.js
  src/libs/axios/auth/index.js
  src/libs/axios/base/axios-instance.js
  src/libs/axios/base/index.js
  src/libs/axios/base/products.js
  src/libs/msw/browser.js
  src/libs/msw/database/index.js
  src/libs/msw/database/market-conditions.json
  src/libs/msw/database/products.json
  src/libs/msw/database/users.json
  src/libs/msw/handlers.js
  src/libs/msw/services/commons.js
  src/libs/msw/services/index.js
  src/libs/msw/services/products.js
Labels: feat

#43 PR: RouterProvider 삭제된 모듈 복원
  src/index.js
Labels: fix

#44 PR: icon-and-text컴포넌트 변경사항있어서 수정했습니다.
  src/components/commons/icon-and-text.jsx
Labels: design

#47 PR: modal-common 배경및 button 기본 기능변경
  src/components/overlay/index.js
  src/components/overlay/modal.jsx
Labels: fix

#40 PR/PD-46: feat/login 로직 기능 구현
  src/constants/index.js
  src/constants/token-key.js
  src/libs/react-router-dom/admin-router.jsx
  src/pages/signin-page.jsx
  src/utils/index.js
  src/utils/storage-manager.js
Labels: feat

#46 PR/PD-70: 상품등록페이지 퍼블리싱 완료했습니다.
  src/components/commons/highlighted-text.jsx
  src/components/register-product/categories-selector.jsx
  src/components/register-product/detail-text-area.jsx
  src/components/register-product/image-loader.jsx
  src/components/register-product/index.js
  src/components/register-product/location-picker.jsx
  src/components/register-product/page-notice.jsx
  src/components/register-product/payment-method-toggle.jsx
  src/components/register-product/register-section.jsx
  src/constants/categories.js
  src/constants/index.js
  src/libs/styled-components/global-styles.jsx
  src/pages/register-product-page.jsx
Labels: design

#49 PR/PD-80: 모달 컴포넌트 리펙토링 진행했습니다.
  src/components/overlay/modal.jsx
Labels: refactor

#52 PR/PD-56: design/chatting-overlay-common 다시 PR 올립니다.
  src/components/commons/search-bar.jsx
  src/components/commons/side-chat-button.jsx
  src/components/layouts/header.jsx
  src/components/overlay/chatting/chat-room-list.jsx
  src/components/overlay/chatting/chat.jsx
  src/components/overlay/chatting/chatting-overlay.jsx
  src/components/overlay/chatting/index.js
Labels: design

#58 PR/PD-80: 모달 컴포넌트 border 추가 등 작업했습니다.
  src/components/overlay/modal.jsx
Labels: refactor, design

#57 PR: eight-product-grid를 공용 컴포넌트로 변경하였습니다
  src/components/commons/eight-product-grid.jsx
  src/components/commons/index.js
  src/components/product-list/eight-product-grid.jsx
  src/components/product-list/index.js
  src/pages/product-list-page.jsx
Labels: fix

#59 PR: text-spacer 생성했습니다
  src/components/commons/index.js
  src/components/commons/text-spacer.jsx
Labels: design

#54 PR/PD-82: react-query 의존성 추가 및 설정, 상품 데이터 캐싱 함수 작성했습니다.
  package-lock.json
  package.json
  src/constants/index.js
  src/constants/query-key.js
  src/index.js
  src/libs/axios/base/products.js
  src/libs/react-query/index.js
  src/libs/react-query/products.js
Labels: feat, config

#61 PR: 삭제된 chart-calculator.js index에서 삭제
  src/utils/index.js
Labels: fix

#53 PR/PD-58: signup-page 기능 완료했습니다
  src/constants/validate-message.js
  src/pages/signup-page.jsx
  src/utils/check-duplication.js
  src/utils/index.js
Labels: feat

#33 PR/PD-77: 회원정보수정 오버레이 모달을 생성했습니다.
  src/components/overlay/edit-user-info-window.jsx
  src/components/overlay/index.js
Labels: design

#62 PR/PD-83: 공용컴포넌트 "CenterBox" 작성했습니다.
  src/components/commons/center-box.jsx
  src/components/commons/index.js
Labels: design

#60 PR: publish-main searchbar 수정했습니다.
  src/components/layouts/header.jsx
  src/components/product-list/promotion-banner.jsx
  src/pages/product-list-page.jsx
Labels: fix

#55 PR/PD-71: used-product 페이지 퍼블리싱 완료했습니다.
  src/components/used-product/index.js
  src/components/used-product/used-free-list.jsx
  src/pages/index.js
  src/pages/used-product-page.jsx
Labels: design

#63 PR: 로그인 로직 수정 및 axios-instance수정 및 user.js api 페이지 생성
  package-lock.json
  package.json
  src/components/overlay/edit-user-info-window.jsx
  src/constants/validate-message.js
  src/libs/axios/auth/index.js
  src/libs/axios/auth/storage-manager.js
  src/libs/axios/base/axios-instance.js
  src/libs/axios/base/index.js
  src/libs/axios/base/user.js
  src/libs/react-router-dom/admin-router.jsx
  src/pages/signin-page.jsx
  src/pages/signup-page.jsx
  src/utils/index.js
  src/utils/storage-manager.js
Labels: feat, fix

#66 PR: chat api 생성했습니다.
  src/libs/axios/base/chat.js
  src/libs/axios/base/index.js
Labels: feat

#65 PR/PD-60: myPage컴포넌트 작업완료했습니다
  src/components/layouts/header.jsx
  src/components/my-info/graph-section.jsx
  src/components/my-info/index.js
  src/components/my-info/infomation-section.jsx
  src/components/my-info/manage-products-section.jsx
  src/components/my-info/product-list-section.jsx
  src/components/my-info/transactions-card.jsx
  src/pages/my-info-page.jsx
Labels: design

#68 PR: Product API 생성했습니다.
  src/libs/axios/base/products.js
Labels: feat
